# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1


# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: echo "this is the test job"

  compile:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: gcc Tests.c -o Tests -lm


          
# Orchestrate or schedule a set of jobs
workflows:
  
  build_and_test:
    jobs:
      - build
      - test

  compile_and_link:
    jobs:
      - compile

