# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

executors:
  my-executor:
    docker:
      - image: gcc:8.2
    working_directory: /build
  
  
# Define the jobs we want to run for this project
jobs:
  compile:
    executor: my-executor
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: mkdir testing
      - run: gcc Tests.c -o Tests -lm
      - run: mv Tests testing
      
      - persist_to_workspace:
          root: testing
          paths:
            - Tests
        

  test:
    executor: my-executor
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - attach_workspace:
          at: /build/testing
          
      - run: ./testing/Tests

          
# Orchestrate or schedule a set of jobs
workflows:

  compile_and_test:
    jobs:
      - compile
      - test:
          requires: 
            - compile
      

